
[server]
port = 5000
enableCORS = false
enableXsrfProtection = false
headless = true
address = "0.0.0.0"

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
